version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
  php:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
  admin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - '8080:80'
    links:
      - mysql:db
    depends_on:
      - mysql
volumes:
  db:
